### ISSUE TITLE
Altering column charset fails on binlog apply

### ISSUE THREAD

**Issue by pbitty** [github/gh-ost#235]
I am trying to alter the charset of a column.  This is something we're doing with many of our tables - in most cases we're going `utf8` --> `utf8mb4`, which is working with no problems.

When going `latin1` --> `utf8mb4`, gh-ost fails when applying binlog statements.

I've been able to reproduce it with this [test case](https://github.com/github/gh-ost/commit/8c7e9da2c5bc5d2e8e780ee4b7c049d129996b9f) in `localtests/`.

This is the output from the test:

```
fe42faeebb20:/go/src/github.com/github/gh-ost# ./localtests/test.sh alter-charset; cat /tmp/gh-ost-test.log
Testing: alter-charset.....
ERROR alter-charset execution failure. cat /tmp/gh-ost-test.log
+ FAIL
2016-09-13 18:14:30 INFO starting gh-ost
2016-09-13 18:14:30 INFO Migrating `test`.`gh_ost_test`
2016-09-13 18:14:30 INFO connection validated on facddf95a8b4:3306
2016-09-13 18:14:30 INFO User has ALL privileges
2016-09-13 18:14:30 INFO binary logs validated on facddf95a8b4:3306
2016-09-13 18:14:30 INFO Restarting replication on facddf95a8b4:3306 to make sure binlog settings apply to replication thread
2016-09-13 18:14:30 DEBUG Replication restarted
2016-09-13 18:14:30 INFO Table found. Engine=InnoDB
2016-09-13 18:14:30 DEBUG Estimated number of rows via STATUS: 21
2016-09-13 18:14:30 DEBUG Validated no foreign keys exist on table
2016-09-13 18:14:30 DEBUG Validated no triggers exist on table
2016-09-13 18:14:30 INFO Estimated number of rows via EXPLAIN: 21
2016-09-13 18:14:30 DEBUG Potential unique keys in gh_ost_test: [PRIMARY (auto_increment): [id]; has nullable: false]
2016-09-13 18:14:30 DEBUG Looking for master on facddf95a8b4:3306
2016-09-13 18:14:30 DEBUG Master of facddf95a8b4:3306 is master:3306
2016-09-13 18:14:30 DEBUG Looking for master on master:3306
2016-09-13 18:14:30 INFO --test-on-replica or --migrate-on-replica given. Will not execute on master master:3306 but rather on replica facddf95a8b4:3306 itself
2016-09-13 18:14:30 INFO binary logs updates validated on facddf95a8b4:3306
2016-09-13 18:14:30 INFO Master found to be facddf95a8b4:3306
2016-09-13 18:14:30 INFO connection validated on facddf95a8b4:3306
2016-09-13 18:14:30 DEBUG Streamer binlog coordinates: mysql-bin.000020:799460
2016-09-13 18:14:30 INFO Registering replica at facddf95a8b4:3306
2016-09-13 18:14:31 INFO Connecting binlog streamer at mysql-bin.000020:799460
2016-09-13 18:14:31 DEBUG Beginning streaming
2016-09-13 18:14:31 INFO connection validated on facddf95a8b4:3306
2016-09-13 18:14:31 INFO rotate to next log name: mysql-bin.000020
2016-09-13 18:14:31 INFO connection validated on facddf95a8b4:3306
2016-09-13 18:14:31 INFO Droppping table `test`.`_gh_ost_test_gho`
2016-09-13 18:14:31 INFO Table dropped
2016-09-13 18:14:31 INFO Droppping table `test`.`_gh_ost_test_ght`
2016-09-13 18:14:31 INFO Table dropped
2016-09-13 18:14:31 INFO Droppping table `test`.`_gh_ost_test_ghc`
2016-09-13 18:14:31 INFO Table dropped
2016-09-13 18:14:31 INFO Creating changelog table `test`.`_gh_ost_test_ghc`
2016-09-13 18:14:31 INFO Changelog table created
2016-09-13 18:14:31 INFO Creating ghost table `test`.`_gh_ost_test_gho`
2016-09-13 18:14:31 INFO Ghost table created
2016-09-13 18:14:31 INFO Altering ghost table `test`.`_gh_ost_test_gho`
2016-09-13 18:14:31 DEBUG ALTER statement: alter /* gh-ost */ table `test`.`_gh_ost_test_gho` MODIFY `t` varchar(128) CHARACTER SET utf8mb4 NOT NULL
2016-09-13 18:14:31 INFO Ghost table altered
2016-09-13 18:14:31 INFO Waiting for tables to be in place
2016-09-13 18:14:31 DEBUG Tables are in place
2016-09-13 18:14:31 DEBUG Received state TablesInPlace
2016-09-13 18:14:31 DEBUG Potential unique keys in _gh_ost_test_gho: [PRIMARY (auto_increment): [id]; has nullable: false]
2016-09-13 18:14:31 INFO Chosen shared unique key is PRIMARY
2016-09-13 18:14:31 INFO Shared columns are id,t
2016-09-13 18:14:31 INFO Listening on unix socket file: /tmp/gh-ost.test.sock
2016-09-13 18:14:31 INFO As instructed, I'm issuing a SELECT COUNT(*) on the table. This may take a while
2016-09-13 18:14:31 INFO Exact number of rows via COUNT: 24
2016-09-13 18:14:31 DEBUG Reading migration range according to key: PRIMARY
2016-09-13 18:14:31 INFO Migration min values: [1]
2016-09-13 18:14:31 DEBUG Reading migration range according to key: PRIMARY
2016-09-13 18:14:31 INFO Migration max values: [24]
2016-09-13 18:14:31 INFO Waiting for first throttle metrics to be collected
2016-09-13 18:14:31 DEBUG Operating until row copy is complete
2016-09-13 18:14:31 DEBUG Getting nothing in the write queue. Sleeping...
# Migrating `test`.`gh_ost_test`; Ghost table is `test`.`_gh_ost_test_gho`
# Migrating facddf95a8b4:3306; inspecting facddf95a8b4:3306; executing on fe42faeebb20
# Migration started at Tue Sep 13 18:14:30 +0000 2016
# chunk-size: 1000; max-lag-millis: 1500ms; max-load: ; critical-load: ; nice-ratio: 0.000000
# throttle-additional-flag-file: /tmp/gh-ost.throttle
# throttle-query: select timestampdiff(second, min(last_update), now()) < 5 from _gh_ost_test_ghc
# Serving on unix socket: /tmp/gh-ost.test.sock
Copy: 0/24 0.0%; Applied: 0; Backlog: 0/100; Time: 0s(total), 0s(copy); streamer: mysql-bin.000020:801748; State: migrating; ETA: N/A
Copy: 0/24 0.0%; Applied: 0; Backlog: 3/100; Time: 1s(total), 1s(copy); streamer: mysql-bin.000020:803876; State: throttled, throttle-query; ETA: N/A
Copy: 0/24 0.0%; Applied: 0; Backlog: 6/100; Time: 2s(total), 2s(copy); streamer: mysql-bin.000020:805552; State: throttled, throttle-query; ETA: N/A
Copy: 0/24 0.0%; Applied: 0; Backlog: 9/100; Time: 3s(total), 3s(copy); streamer: mysql-bin.000020:807228; State: throttled, throttle-query; ETA: N/A
Copy: 0/24 0.0%; Applied: 0; Backlog: 12/100; Time: 4s(total), 4s(copy); streamer: mysql-bin.000020:808904; State: throttled, throttle-query; ETA: N/A
Copy: 0/24 0.0%; Applied: 0; Backlog: 15/100; Time: 5s(total), 5s(copy); streamer: mysql-bin.000020:810581; State: throttled, throttle-query; ETA: N/A
2016-09-13 18:14:36 ERROR Error 1366: Incorrect string value: '\xE1testi...' for column 't' at row 1; query=
       			replace /* gh-ost `test`.`_gh_ost_test_gho` */ into
       				`test`.`_gh_ost_test_gho`
       					(`id`, `t`)
       				values
       					(?, ?)
       		; args=[26 �testing]
goroutine 55 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
       	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
       	/usr/local/go/src/runtime/debug/stack.go:16 +0x18
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.logErrorEntry(0x2, 0x7f92b3736028, 0xc820203420, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:178 +0x159
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.Errore(0x7f92b3736028, 0xc820203420, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:224 +0x40
github.com/github/gh-ost/go/logic.(*Applier).ApplyDMLEventQuery(0xc82016e5c0, 0xc8200f3680, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/go/logic/applier.go:891 +0x358
github.com/github/gh-ost/go/logic.(*Migrator).addDMLEventsListener.func1.1(0x0, 0x0)
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:1025 +0x39
github.com/github/gh-ost/go/logic.(*Migrator).retryOperation(0xc8200b3900, 0xc8201abb20, 0x0, 0x0, 0x0, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:144 +0x74
github.com/github/gh-ost/go/logic.(*Migrator).executeWriteFuncs(0xc8200b3900, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:1146 +0x148
created by github.com/github/gh-ost/go/logic.(*Migrator).Migrate
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:334 +0x979
2016-09-13 18:14:36 ERROR Error 1366: Incorrect string value: '\xE1testi...' for column 't' at row 1; query=
       			replace /* gh-ost `test`.`_gh_ost_test_gho` */ into
       				`test`.`_gh_ost_test_gho`
       					(`id`, `t`)
       				values
       					(?, ?)
       		; args=[26 �testing]
goroutine 55 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
       	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
       	/usr/local/go/src/runtime/debug/stack.go:16 +0x18
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.logErrorEntry(0x2, 0x7f92b3736028, 0xc820203420, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:178 +0x159
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.Errore(0x7f92b3736028, 0xc820203420, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:224 +0x40
github.com/github/gh-ost/go/logic.(*Migrator).executeWriteFuncs(0xc8200b3900, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:1147 +0x174
created by github.com/github/gh-ost/go/logic.(*Migrator).Migrate
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:334 +0x979
2016-09-13 18:14:36 FATAL Error 1366: Incorrect string value: '\xE1testi...' for column 't' at row 1; query=
       			replace /* gh-ost `test`.`_gh_ost_test_gho` */ into
       				`test`.`_gh_ost_test_gho`
       					(`id`, `t`)
       				values
       					(?, ?)
       		; args=[26 �testing]
goroutine 8 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
       	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
       	/usr/local/go/src/runtime/debug/stack.go:16 +0x18
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.logErrorEntry(0x0, 0x7f92b3736028, 0xc820203420, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:178 +0x159
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.Fatale(0x7f92b3736028, 0xc820203420, 0x0, 0x0)
       	/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:255 +0x40
github.com/github/gh-ost/go/logic.(*Migrator).listenOnPanicAbort(0xc8200b3900)
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:221 +0x69
created by github.com/github/gh-ost/go/logic.(*Migrator).Migrate
       	/go/src/github.com/github/gh-ost/go/logic/migrator.go:275 +0x325
exit status 1
*************************** 1. row ***************************
       Table: _gh_ost_test_gho
Create Table: CREATE TABLE `_gh_ost_test_gho` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `t` varchar(128) CHARACTER SET utf8mb4 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8
```

This seems related to #226, but in this case I am altering the charset of the column.  I am still investigating, but I'm posting the issue in case anyone has any ideas.

**Comment by shlomi-noach** [comment]
Are you able to paste the `show create table` for both original and `_gho` table?

**Comment by shlomi-noach** [comment]
I'll take your local tests and try to reproduce. Will likely only work on this next week.

**Comment by pbitty** [comment]
Original:
```
$ mysql -h slave-1 -D test -E -e 'show create table gh_ost_test';
*************************** 1. row ***************************
       Table: gh_ost_test
Create Table: CREATE TABLE `gh_ost_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `t` varchar(128) CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=184 DEFAULT CHARSET=utf8
```

_gho:

```
$ mysql -h slave-1 -D test -E -e 'show create table _gh_ost_test_gho';
*************************** 1. row ***************************
       Table: _gh_ost_test_gho
Create Table: CREATE TABLE `_gh_ost_test_gho` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `t` varchar(128) CHARACTER SET utf8mb4 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8
```

**Comment by pbitty** [comment]
Thanks @shlomi-noach.

I've updated the [local tests](https://github.com/github/gh-ost/commit/8c7e9da2c5bc5d2e8e780ee4b7c049d129996b9f) above.  Added `default charset utf8` to the table, as that's more reflective of our use-case.  I don't think it makes a difference because we're being explicit about the column's charset.

I'll keep investigating as well and post here if I find anything.

**Comment by shlomi-noach** [comment]
Actually your local test succeeds on my local machine

**Comment by shlomi-noach** [comment]
No, my mistake, wasn't running it properly. It fails as you describe.

**Comment by pbitty** [comment]
So far I've traced the issue to the [loop](https://github.com/github/gh-ost/blob/eac6a726de4440faa155f8074f265107c2fb429f/go/sql/builder.go#L347-L351) that builds the insert DML query:

```go
for _, column := range mappedSharedColumns.Columns() {
	tableOrdinal := tableColumns.Ordinals[column.Name]
	arg := column.convertArg(args[tableOrdinal])
	sharedArgs = append(sharedArgs, arg)
}
```

The column in `mappedSharedColumns` has the `Charset` of the target column, not the source.  So in the case where we're converting from `latin1` to `utfmb4` for example, `column.Charset == "utf8mb4"` and so it doesn't convert the value of the source column (which is in `latin1`).

I think the same applies to `BuildDMLUpdateQuery`.

**Comment by shlomi-noach** [comment]
Oh, tracing down will lead you to: https://github.com/github/gh-ost/blob/master/go/sql/types.go#L21
that's where the conversions go. And apparently to convert _to_ `utf8` you need an Encoder instead of Decoder (or vice versa -- my code translates just the opposite from the [documentation](https://godoc.org/golang.org/x/text/encoding))

**Comment by pbitty** [comment]
I think the issue is on the decoding side, more specifically, the lack of a decode operation.

As a quick hack, I referenced the source column in that loop and the tests pass:

```go
for _, column := range mappedSharedColumns.Columns() {
  tableOrdinal := tableColumns.Ordinals[column.Name]
  column = tableColumns.Columns()[tableOrdinal]
  arg := column.convertArg(args[tableOrdinal])
  sharedArgs = append(sharedArgs, arg)
}
```

I added some `fmt.Printf` debug statements and I saw that previously (before the above hack), it was considering the source column's `Charset` as `utf8mb4`, even though the charset is actually `latin1`.  So it was reading the source value without decoding it, letting Go treat the bytes as `utf8`, which failed on the insert.

**Comment by pbitty** [comment]
I added these debug statements in `builder.go:347`:

```go
for _, column := range mappedSharedColumns.Columns() {
  tableOrdinal := tableColumns.Ordinals[column.Name]
  fmt.Printf("[DEBUG] column: %#v\n", column)
  originalArg := args[tableOrdinal]
  fmt.Printf("[DEBUG] BEFORE CONVERT --> name: %v, value: %v\n", column.Name, originalArg)
  arg := column.convertArg(originalArg)
  fmt.Printf("[DEBUG] AFTER CONVERT  --> name: %v, value: %v\n", column.Name, arg)
  sharedArgs = append(sharedArgs, arg)
}
```

Using `--alter='engine=INNODB'`:

```
[DEBUG] column: sql.Column{Name:"t", IsUnsigned:false, Charset:"latin1"}
[DEBUG] BEFORE CONVERT --> name: t, value: �testing
[DEBUG] AFTER CONVERT  --> name: t, value: átesting
```

Using `--alter='MODIFY `t` varchar(128) CHARACTER SET utf8mb4 NOT NULL'`:

```
[DEBUG] column: sql.Column{Name:"t", IsUnsigned:false, Charset:"utf8mb4"}
[DEBUG] BEFORE CONVERT --> name: t, value: �testing
[DEBUG] AFTER CONVERT  --> name: t, value: �testing
```

Using `--alter='MODIFY `t` varchar(128) CHARACTER SET utf16 NOT NULL'`:

```
[DEBUG] column: sql.Column{Name:"t", IsUnsigned:false, Charset:"utf16"}
[DEBUG] BEFORE CONVERT --> name: t, value: �testing
[DEBUG] AFTER CONVERT --> name: t, value: �testing
```

The `column.Charset` is following the charset of the `_gho` table, which is changed by the alter statement, set [here](https://github.com/github/gh-ost/blob/eac6a726de4440faa155f8074f265107c2fb429f/go/logic/inspect.go#L139).

**Comment by pbitty** [comment]
Discussing potential fix in #236 .

**Comment by shlomi-noach** [comment]
Apologies for the delay. Was recovering from Jetlag and did not want to address this while semi-awake. This is high on my priority list.

**Comment by shlomi-noach** [comment]
> I think the same applies to BuildDMLUpdateQuery.

I've just added `alter-charset-all-dml` where `update` statements do indeed fail.
