### ISSUE TITLE
panic on master-master setup when on-failure hook exists

### ISSUE THREAD

**Issue by jbodah** [github/gh-ost#256]
Had a master-master setup and a simple `echo hello` hook (and a `on-startup` hook which worked fine). `gh-ost` errored out on the master-master setup and then hit a panic when trying to run the failure hook. Removing the hook allowed `gh-ost` to gracefully fail and tell me that the master-master setup was the problem.

Version 1.0.20, Ubuntu 14.04, installed from release tarball

```
#! /usr/bin/env sh
# hooks/gh-ost-on-failure
echo hello
```

Running gh-ost with the following:

```
gh-ost --database=my_database --conf=my_conf.cnf --table=my_table --alter='ADD COLUMN some_col int' --hooks-path=hooks --hooks-hint=my_name --verbose --switch-to-rbr --test-on-replica --execute --debug
```

Caused a panic:

```
2016-10-03 14:11:22 INFO starting gh-ost 1.0.20
2016-10-03 14:11:22 INFO Migrating `my_database`.`my_table`
2016-10-03 14:11:22 INFO executing gh-ost-on-startup hook: hooks/gh-ost-on-startup--tell-slack
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   310  100     2  100   308      9   1418 --:--:-- --:--:-- --:--:--  1419
ok
2016-10-03 14:11:22 INFO connection validated on xxx.xxx.xxx.xxx:3306
2016-10-03 14:11:22 INFO User has SUPER, REPLICATION SLAVE privileges, and has ALL privileges on `my_database`.*
2016-10-03 14:11:22 INFO binary logs validated on xxx.xxx.xxx.xxx:3306
2016-10-03 14:11:22 INFO Restarting replication on xxx.xxx.xxx.xxx:3306 to make sure binlog settings apply to replication thread
2016-10-03 14:11:22 DEBUG Replication restarted
2016-10-03 14:11:22 INFO Table found. Engine=InnoDB
2016-10-03 14:11:22 DEBUG Estimated number of rows via STATUS: 177523871
2016-10-03 14:11:23 DEBUG Validated no foreign keys exist on table
2016-10-03 14:11:23 DEBUG Validated no triggers exist on table
2016-10-03 14:11:23 INFO Estimated number of rows via EXPLAIN: 191585167
2016-10-03 14:11:23 DEBUG Potential unique keys in tasks: [PRIMARY (auto_increment): [id]; has nullable: false]
2016-10-03 14:11:23 DEBUG Looking for master on xxx.xxx.xxx.xxx:3306
2016-10-03 14:11:23 DEBUG Master of xxx.xxx.xxx.xxx:3306 is xxx.xxx.xxx.xxx:3306
2016-10-03 14:11:23 DEBUG Looking for master on xxx.xxx.xxx.xxx:3306
2016-10-03 14:11:23 DEBUG Master of xxx.xxx.xxx.xxx:3306 is xxx.xxx.xxx.xxx:3306
2016-10-03 14:11:23 DEBUG Looking for master on xxx.xxx.xxx.xxx:3306
2016-10-03 14:11:23 DEBUG Master of xxx.xxx.xxx.xxx:3306 is xxx.xxx.xxx.xxx:3306
2016-10-03 14:11:23 INFO executing gh-ost-on-failure hook: hooks/gh-ost-on-failure
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x4a436f]

goroutine 1 [running]:
panic(0x797b60, 0xc82000e0c0)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/github/gh-ost/go/logic.(*HooksExecutor).applyEnvironmentVairables(0xc820082088, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/go/logic/hooks.go:62 +0xf2f
github.com/github/gh-ost/go/logic.(*HooksExecutor).executeHook(0xc820082088, 0xc82014ac20, 0x17, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/go/logic/hooks.go:77 +0xa2
github.com/github/gh-ost/go/logic.(*HooksExecutor).executeHooks(0xc820082088, 0x84b940, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/go/logic/hooks.go:100 +0x2e9
github.com/github/gh-ost/go/logic.(*HooksExecutor).onFailure(0xc820082088, 0x0, 0x0)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/go/logic/hooks.go:144 +0x53
github.com/github/gh-ost/go/logic.(*Migrator).ExecOnFailureHook(0xc8200a03f0, 0x0, 0x0)
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/go/logic/migrator.go:362 +0x33
main.main()
        /Users/shlomi-noach/dev/go/src/github.com/github/gh-ost/go/cmd/gh-ost/main.go:212 +0x1f6e
```

**Comment by shlomi-noach** [comment]
Thank you -- I'll look into it.
To clarify, this is not a Kernel Panic. It's a `gh-ost` app panic on nil pointer reference.

**Comment by jbodah** [comment]
Woops, of course 😝

**Comment by shlomi-noach** [comment]
The error originates from https://github.com/github/gh-ost/blob/master/go/logic/hooks.go#L62-L63, where we assume `ImpliedKey` exists and has a `Hostname`.

This is not the case in the early stages of the app. In particular, in this issue's particular case, `gh-ost` bails out while searching for the master, so clearly no applier exists.

**Comment by shlomi-noach** [comment]
closed by https://github.com/github/gh-ost/pull/260
