### ISSUE TITLE
running gh-ost on table with json datatype 

### ISSUE THREAD

**Issue by lioraltarescu** [github/gh-ost#916]
Hello ,  I'm trying to alter a table with json column and a stored virtual column . 

My setup is 4 mysql server 8.0.22 , where two of them are comaster and each comaster has a slave . Only one comaster is open to writes. 

this is the table 
```
 CREATE TABLE `a` (
  `id` varbinary(16) NOT NULL,
  `idb` varchar(36) CHARACTER SET latin1 COLLATE latin1_swedish_ci GENERATED ALWAYS AS (json_unquote(json_extract(`jsonobj`,_utf8mb4'$._id'))) STORED NOT NULL,
  `jsonobj` json NOT NULL,
  PRIMARY KEY (`id`,`idb`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED
```

My end goal is to modify the virtual stored column and PK but i get a go driver error when I try to add a simple column 
here is my gh-ost command
```
  /usr/bin/gh-ost    \
 --max-load='Threads_running=500'    \
 --critical-load='Threads_running=1000'    \
 --initially-drop-ghost-table    \
 --initially-drop-old-table    \
 --chunk-size=600    \
 --max-lag-millis=3000    \
 --user='ghostuser'   \
 --password='password'   \
 --assume-master-host='writablecomaster'   \
 --throttle-control-replicas='othercomaster'   \
 --host='comasterslave'  \
 --database=a   \
 --table=b   \
 --verbose    \
 --alter="add yeet varchar(20)"    \
 --assume-rbr    \
 --allow-master-master    \
 --cut-over=default    \
 --concurrent-rowcount    \
 --default-retries=4000    \
 --panic-flag-file=/tmp/ghost.panic.flag    \
 --exact-rowcount    \
 --postpone-cut-over-flag-file=/tmp/ghost.postpone.flag 
 ```
 I get the error in the in the dry run 
 ```
 2021-01-14 12:30:38 INFO Waiting for ghost table to be migrated. Current lag is 0s
2021-01-14 12:30:38 INFO Intercepted changelog state GhostTableMigrated
2021-01-14 12:30:38 INFO Handled changelog state GhostTableMigrated
2021-01-14 12:30:38 INFO Chosen shared unique key is PRIMARY
2021-01-14 12:30:38 INFO Shared columns are tenant_id,entity
2021-01-14 12:30:38 INFO Tearing down inspector
2021-01-14 12:30:38 INFO Tearing down applier
2021-01-14 12:30:38 INFO Tearing down streamer
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x723e6d]

goroutine 1 [running]:
github.com/github/gh-ost/go/sql.(*ColumnList).HasTimezoneConversion(...)
	/go/src/github.com/github/gh-ost/go/sql/types.go:179
github.com/github/gh-ost/go/logic.(*Inspector).inspectOriginalAndGhostTables(0xc00000ec00, 0x801668, 0x14)
	/go/src/github.com/github/gh-ost/go/logic/inspect.go:187 +0xb9d
github.com/github/gh-ost/go/logic.(*Migrator).Migrate(0xc0000c21b0, 0x0, 0x0)
	/go/src/github.com/github/gh-ost/go/logic/migrator.go:361 +0x54e
main.main()
	/go/src/github.com/github/gh-ost/go/cmd/gh-ost/main.go:293 +0x2962
```

**Comment by shlomi-noach** [comment]
I'm going to look into this out of interest.

**Comment by shlomi-noach** [comment]
@lioraltarescu can you please provide some simplified table data so I can create a test case?

**Comment by shlomi-noach** [comment]
@lioraltarescu please test this binary: https://github.com/openark/gh-ost/suites/1856467417/artifacts/36046306, built by https://github.com/openark/gh-ost/actions/runs/495894244 as part of https://github.com/openark/gh-ost/pull/13

### Please make sure to test on replica and not on production

While the new test suite passes. please let me know if this fixes your problem and please validate the data is intact.

**Comment by lioraltarescu** [comment]
hey @shlomi-noach  we tested it and it solved the issue. 10x A lot !!

**Comment by shlomi-noach** [comment]
Cool. Just as long as you double and triple check data integrity.

I will submit this PR upstream.

**Comment by lioraltarescu** [comment]
ok , got it .  We checked our use case that we ran into a couple of time but we will check other use case that we had in the past to see everything is ok and update you . 10x

**Comment by davidlwpblo** [comment]
![IMG_20210126_152047_223.jpg](https://user-images.githubusercontent.com/78993986/108714933-6e2a7900-74d7-11eb-89e5-f740e8d49c03.jpg).          This is basically discrimination racism sexism cyberbullying disrespect to the disability act. Black lives do matter you're not aware this is Black History month. All black men and women are never seen as victims under any circumstances it's clear throughout history. I've submitted all kind of verifications email's etc you and your staff are ignoring that a new member that recently joined post    from his profile are detailed. It's clear signs he may be a victim bye a long-term member involving others such gang related activities publicly. You and your staff have verified evidence of favoritism regarding the involved person that put my life in harm with false allegations statements I've been ignored misled explored etc .

**Comment by davidlwpblo** [comment]
> Hello ,  I'm trying to alter a table with json column and a stored virtual column . 
> 
> My setup is 4 mysql server 8.0.22 , where two of them are comaster and each comaster has a slave . Only one comaster is open to writes. 
> 
> this is the table 
> ```
>  CREATE TABLE `a` (
>   `id` varbinary(16) NOT NULL,
>   `idb` varchar(36) CHARACTER SET latin1 COLLATE latin1_swedish_ci GENERATED ALWAYS AS (json_unquote(json_extract(`jsonobj`,_utf8mb4'$._id'))) STORED NOT NULL,
>   `jsonobj` json NOT NULL,
>   PRIMARY KEY (`id`,`idb`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED
> ```
> 
> My end goal is to modify the virtual stored column and PK but i get a go driver error when I try to add a simple column 
> here is my gh-ost command
> ```
>   /usr/bin/gh-ost    \
>  --max-load='Threads_running=500'    \
>  --critical-load='Threads_running=1000'    \
>  --initially-drop-ghost-table    \
>  --initially-drop-old-table    \
>  --chunk-size=600    \
>  --max-lag-millis=3000    \
>  --user='ghostuser'   \
>  --password='password'   \
>  --assume-master-host='writablecomaster'   \
>  --throttle-control-replicas='othercomaster'   \
>  --host='comasterslave'  \
>  --database=a   \
>  --table=b   \
>  --verbose    \
>  --alter="add yeet varchar(20)"    \
>  --assume-rbr    \
>  --allow-master-master    \
>  --cut-over=default    \
>  --concurrent-rowcount    \
>  --default-retries=4000    \
>  --panic-flag-file=/tmp/ghost.panic.flag    \
>  --exact-rowcount    \
>  --postpone-cut-over-flag-file=/tmp/ghost.postpone.flag 
>  ```
>  I get the error in the in the dry run 
>  ```
>  2021-01-14 12:30:38 INFO Waiting for ghost table to be migrated. Current lag is 0s
> 2021-01-14 12:30:38 INFO Intercepted changelog state GhostTableMigrated
> 2021-01-14 12:30:38 INFO Handled changelog state GhostTableMigrated
> 2021-01-14 12:30:38 INFO Chosen shared unique key is PRIMARY
> 2021-01-14 12:30:38 INFO Shared columns are tenant_id,entity
> 2021-01-14 12:30:38 INFO Tearing down inspector
> 2021-01-14 12:30:38 INFO Tearing down applier
> 2021-01-14 12:30:38 INFO Tearing down streamer
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x723e6d]
> 
> goroutine 1 [running]:
> github.com/github/gh-ost/go/sql.(*ColumnList).HasTimezoneConversion(...)
> 	/go/src/github.com/github/gh-ost/go/sql/types.go:179
> github.com/github/gh-ost/go/logic.(*Inspector).inspectOriginalAndGhostTables(0xc00000ec00, 0x801668, 0x14)
> 	/go/src/github.com/github/gh-ost/go/logic/inspect.go:187 +0xb9d
> github.com/github/gh-ost/go/logic.(*Migrator).Migrate(0xc0000c21b0, 0x0, 0x0)
> 	/go/src/github.com/github/gh-ost/go/logic/migrator.go:361 +0x54e
> main.main()
> 	/go/src/github.com/github/gh-ost/go/cmd/gh-ost/main.go:293 +0x2962
> ```

![Screenshot_20210211-223813.png](https://user-images.githubusercontent.com/78993986/108715155-b21d7e00-74d7-11eb-8f02-c4dc913d7e67.png)

**Comment by davidlwpblo** [comment]
I have complained time and time again about this man and no one will listen to me when is someone going to listen to me this man is a hacker and a mastermind manipulator

**Comment by shlomi-noach** [comment]
Irrespective of some spam comments on this issue, I recommend closing it, given https://github.com/openark/gh-ost/pull/13 has been merged.

**Comment by davidlwpblo** [comment]
![Screenshot_20210222-073217.png](https://user-images.githubusercontent.com/78993986/108723430-7b4c6580-74e1-11eb-9ff0-73818e573fec.png).     This is so crazy you guys are conspiring to cover up his everything do you guys have any common sense I don't know what to do about this whole situation I don't even know if I

**Comment by davidlwpblo** [comment]
![Screenshot_20210222-073915.png](https://user-images.githubusercontent.com/78993986/108723879-f6158080-74e1-11eb-95ce-2d7601378b45.png).    Dear general public if you reviewing this message this is totally inappropriate the platform is helping a cyber bully whic the staff is along with the whole situation to harm my self a disabled applicant who just entered the platform by referral I didn't know I was getting myself into this if someone anyone can assist me it will be really decent because this is scary

**Comment by davidlwpblo** [comment]
![Screenshot_20210222-073806.png](https://user-images.githubusercontent.com/78993986/108724319-6f14d800-74e2-11eb-8d38-e58d30f2ea89.png).     I never did anything to harm that man whatsoever and this is what you do to me false false false false everything lies lies lies just to hurt what is your motivation this is crazy hacking into a person's personal hardware and etc so the platform is false

**Comment by davidlwpblo** [comment]
I sincerely apologize to who this may have infected in the impact of this whole situation out of my honesty and Truth may you all have a blessed Black History month black lives do matter is so inappropriate to kick a person when you think they're down all black men and women are never seen as victims so disrespectful

**Comment by davidlwpblo** [comment]
I apologize and I didn't mean anything thing personal about that I was referred from the other company to you guys for some reason I prior had you guys and I put my account on hold and it got deleted or something but you guys are a new company with the other one like a school so I really appreciate it and I never ever meant any harm behind it I just have to be honest and I didn't know that any of your staff was linked to the issue or the problem that was being dealt from the platform under this in the previous entity which is get it or read it or whatever it is but other company that referred me to you guys I mean well they actually switched me over to you guys after they about the problem and the issue they basically did and I guess if you guys can properly file this or we're not it will be greatly appreciated davidleewilliamspablo@centurylink.net  I don't want any retaliation or anything because I am the victim under all circumstances like I originally stated insinuated with the platform originally read it and they ignored me for like 30 to 60 days as I was being you know abused by the staff the high authority I was emailing faxing I even notified Facebook and Twitter nobody took any, heat of it when there was really multiple entities involved and it was because of a hacker that was hacking in my things that was basically working for the platform and he hacked in my Facebook he hacked in my Reddit well the staff was allowing it oh my God he was a mastermind on Twitter and what was so crazy about it is that they did not want to hear me out it wasn't that they wasn't believing me they refuse to take a knowledge of it they didn't care they was like this member and so many ways I'm in words was a member before you pretty much and we don't care whether if you're disabled black none of that and we are aware that you are a victim that's what Reddit Twitter and all of them was pretty much you know coming at me at like oh well we we know you submitted the documents you emailed us and everything



> Thank you!

**Comment by davidlwpblo** [comment]
So basically the platform was connected to your other company and your and the platform was basically and so many words allowing cyberbullying harassing prostitution ECT in so many words they said that since no one can really tell what codeine is or knows how to process it  so what got me at this rate and approach recently I took one of their post off my boyfriend's page I pasted or copied it and then I landed into Google search engine and it was hidden entity which is a hidden conversation of plot against me out of threats if you can basically understand the approach to life out of seriousness and talking in codes amongst one another they left the platform to basically talk about me my boyfriend and some others which is you see the documents there and then they kept stating when I approached the platform with the evidence of a Google processed by flipping the post off of the platform because he was so good of a hacker that he can literally lift that post up go underneath there and have a conversation so the platform wouldn't be able to see or anyone to discover and when I brought that to the platform Discovery publicly they got high rate at me and etc so I was aware that they did know and they were all in on it and he was so crazy as well was he kept saying this it was last year it was last year do you know today Google do not lie one and you can change time and date on post that's what Killers do

**Comment by davidlwpblo** [comment]
I'm being honest I got to tell you the truth just to protect myself and your company and the reason why is because I'm only acquainted to one person how are these people get involved and my personal affairs you know what I mean and they were not even my personal affairs they were all false allegations and statements assaulting and humiliating me and my health and etc talking about my parents and my background race just racistly inappropriately sexist and etc violently you name it this platform was condoning and going along with it and when I stood up and stick my chest out it wasn't good enough so they retaliated even the staff was familiar okay when I got back into my other cup your other companies profile that I had up there I discovered immediately that it was a link from the platform to your company over there and I was like wow this is a small world you know what I mean like so this is all connected they are hacking me they all cyber bullying me they are taunting me they are threatening me they are making plots because I won't shut my fucking mouth because I want my name to be cleared they won't even make the guy I don't even know he was working for the platformer till recently they wouldn't even serve him with any kind of consequences but whenever they confirmed that he was wrong I got the repercussions meaning I got banned and etc you know what I mean I'm necessary stuff my tablet is in the shop right now getting repair because of the Cincinnati as well I am keeping my internet provider informed as well Samson I have a 65 in the living room which is I got on Halloween and I got one I got in my last house which is a 55 nice decent products that tronics and I don't want anything to happen to my products are to be harmed myself personally and this was publicly known we got some hackers and our communities and we got to be aware and that's what I'm bringing to attention for the senior citizens and the disabled applicants as well black lives do matter I'm protecting myself I've been bullied all my life and I love me and this scares me I live by myself I have no family and friends in the state of Arizona born and raised Los Angeles California so I'm shouting now to see if somebody's can help me get this done properly and the right way I have no intentions of harming or getting anybody fired but consequences got to be served wrong is wrong

**Comment by davidlwpblo** [comment]
![Screenshot_20210218-075054](https://user-images.githubusercontent.com/78993986/108744551-4a772b00-74f7-11eb-8848-02619aceeb17.png)

**Comment by davidlwpblo** [comment]
![Screenshot_20210222-102717.png](https://user-images.githubusercontent.com/78993986/108745853-d9387780-74f8-11eb-878f-d35f64445880.png).            Could you please publicly report this I just happen to get a message right now so I happen to log on I don't know what to do with this this is basically discrimination as I proven to you and your company I'm basically been profiled and I fear for my life

**Comment by shlomi-noach** [comment]
Please close this issue?
